//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace UMeng
{
    /// <summary>
    /// 实体类YM_Activation。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("UMeng_Activation")]
    [Serializable]
    public partial class UMeng_Activation : Entity
    {
        #region Model
        private long _AutoID;
        private string _Mid;
        private string _Active_Id;
        private string _Type;
        private string _Active_Date;
        private string _Click_Date;
        private string _Rp_Name;
        private string _M_Name;
        private string _Chan_Name;

        /// <summary>
        /// 
        /// </summary>
        [Field("AutoID")]
        public long AutoID
        {
            get { return _AutoID; }
            set
            {
                this.OnPropertyValueChange("AutoID");
                this._AutoID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Mid")]
        public string Mid
        {
            get { return _Mid; }
            set
            {
                this.OnPropertyValueChange("Mid");
                this._Mid = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Active_Id")]
        public string Active_Id
        {
            get { return _Active_Id; }
            set
            {
                this.OnPropertyValueChange("Active_Id");
                this._Active_Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Type")]
        public string Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange("Type");
                this._Type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Active_Date")]
        public string Active_Date
        {
            get { return _Active_Date; }
            set
            {
                this.OnPropertyValueChange("Active_Date");
                this._Active_Date = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Click_Date")]
        public string Click_Date
        {
            get { return _Click_Date; }
            set
            {
                this.OnPropertyValueChange("Click_Date");
                this._Click_Date = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Rp_Name")]
        public string Rp_Name
        {
            get { return _Rp_Name; }
            set
            {
                this.OnPropertyValueChange("Rp_Name");
                this._Rp_Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("M_Name")]
        public string M_Name
        {
            get { return _M_Name; }
            set
            {
                this.OnPropertyValueChange("M_Name");
                this._M_Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Chan_Name")]
        public string Chan_Name
        {
            get { return _Chan_Name; }
            set
            {
                this.OnPropertyValueChange("Chan_Name");
                this._Chan_Name = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.AutoID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.AutoID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.AutoID,
                _.Mid,
                _.Active_Id,
                _.Type,
                _.Active_Date,
                _.Click_Date,
                _.Rp_Name,
                _.M_Name,
                _.Chan_Name,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._AutoID,
                this._Mid,
                this._Active_Id,
                this._Type,
                this._Active_Date,
                this._Click_Date,
                this._Rp_Name,
                this._M_Name,
                this._Chan_Name,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "UMeng_Activation");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AutoID = new Field("AutoID", "UMeng_Activation", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Mid = new Field("Mid", "UMeng_Activation", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Active_Id = new Field("Active_Id", "UMeng_Activation", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type", "UMeng_Activation", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Active_Date = new Field("Active_Date", "UMeng_Activation", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Click_Date = new Field("Click_Date", "UMeng_Activation", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Rp_Name = new Field("Rp_Name", "UMeng_Activation", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field M_Name = new Field("M_Name", "UMeng_Activation", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Chan_Name = new Field("Chan_Name", "UMeng_Activation", "");
        }
        #endregion
    }
}