//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Tender.Model
{
    /// <summary>
    /// 实体类ETLStatus。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("ETLStatus")]
    [Serializable]
    public partial class ETLStatus : Entity
    {
        #region Model
        private long _AutoID;
        private string _Key;
        private string _Value;

        /// <summary>
        /// 
        /// </summary>
        [Field("AutoID")]
        public long AutoID
        {
            get { return _AutoID; }
            set
            {
                this.OnPropertyValueChange("AutoID");
                this._AutoID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Key")]
        public string Key
        {
            get { return _Key; }
            set
            {
                this.OnPropertyValueChange("Key");
                this._Key = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Value")]
        public string Value
        {
            get { return _Value; }
            set
            {
                this.OnPropertyValueChange("Value");
                this._Value = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.AutoID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.AutoID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.AutoID,
                _.Key,
                _.Value,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._AutoID,
                this._Key,
                this._Value,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "ETLStatus");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AutoID = new Field("AutoID", "ETLStatus", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Key = new Field("Key", "ETLStatus", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Value = new Field("Value", "ETLStatus", "");
        }
        #endregion
    }
}
