//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Tender.Model
{
    /// <summary>
    /// 实体类H5_Consume_201903。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("H5_Consume_201903")]
    [Serializable]
    public partial class H5_Consume_201903 : Entity
    {
        #region Model
        private long __AutoID_;
        private DateTime __RequestTime_;
        private DateTime __AddTime_;
        private int __PartDay_;
        private DateTime __StatTime_;
        private string __IP_;
        private string __Language_;
        private string __UserAgent_;
        private string _AppID;
        private string _ServerID;
        private string _Type;
        private string _AccountID;
        private string _UserID;
        private string _Number;
        private string _ItemType;
        private string _Price;
        private string _ItemCnt;
        private string _MoneyType;
        private string _IP;
        private int _StatTime;

        /// <summary>
        /// 
        /// </summary>
        [Field("_AutoID_")]
        public long _AutoID_
        {
            get { return __AutoID_; }
            set
            {
                this.OnPropertyValueChange("_AutoID_");
                this.__AutoID_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_RequestTime_")]
        public DateTime _RequestTime_
        {
            get { return __RequestTime_; }
            set
            {
                this.OnPropertyValueChange("_RequestTime_");
                this.__RequestTime_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_AddTime_")]
        public DateTime _AddTime_
        {
            get { return __AddTime_; }
            set
            {
                this.OnPropertyValueChange("_AddTime_");
                this.__AddTime_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_PartDay_")]
        public int _PartDay_
        {
            get { return __PartDay_; }
            set
            {
                this.OnPropertyValueChange("_PartDay_");
                this.__PartDay_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_StatTime_")]
        public DateTime _StatTime_
        {
            get { return __StatTime_; }
            set
            {
                this.OnPropertyValueChange("_StatTime_");
                this.__StatTime_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_IP_")]
        public string _IP_
        {
            get { return __IP_; }
            set
            {
                this.OnPropertyValueChange("_IP_");
                this.__IP_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_Language_")]
        public string _Language_
        {
            get { return __Language_; }
            set
            {
                this.OnPropertyValueChange("_Language_");
                this.__Language_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_UserAgent_")]
        public string _UserAgent_
        {
            get { return __UserAgent_; }
            set
            {
                this.OnPropertyValueChange("_UserAgent_");
                this.__UserAgent_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AppID")]
        public string AppID
        {
            get { return _AppID; }
            set
            {
                this.OnPropertyValueChange("AppID");
                this._AppID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ServerID")]
        public string ServerID
        {
            get { return _ServerID; }
            set
            {
                this.OnPropertyValueChange("ServerID");
                this._ServerID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Type")]
        public string Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange("Type");
                this._Type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AccountID")]
        public string AccountID
        {
            get { return _AccountID; }
            set
            {
                this.OnPropertyValueChange("AccountID");
                this._AccountID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserID")]
        public string UserID
        {
            get { return _UserID; }
            set
            {
                this.OnPropertyValueChange("UserID");
                this._UserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Number")]
        public string Number
        {
            get { return _Number; }
            set
            {
                this.OnPropertyValueChange("Number");
                this._Number = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ItemType")]
        public string ItemType
        {
            get { return _ItemType; }
            set
            {
                this.OnPropertyValueChange("ItemType");
                this._ItemType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Price")]
        public string Price
        {
            get { return _Price; }
            set
            {
                this.OnPropertyValueChange("Price");
                this._Price = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ItemCnt")]
        public string ItemCnt
        {
            get { return _ItemCnt; }
            set
            {
                this.OnPropertyValueChange("ItemCnt");
                this._ItemCnt = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MoneyType")]
        public string MoneyType
        {
            get { return _MoneyType; }
            set
            {
                this.OnPropertyValueChange("MoneyType");
                this._MoneyType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("IP")]
        public string IP
        {
            get { return _IP; }
            set
            {
                this.OnPropertyValueChange("IP");
                this._IP = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("StatTime")]
        public int StatTime
        {
            get { return _StatTime; }
            set
            {
                this.OnPropertyValueChange("StatTime");
                this._StatTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _._AutoID_,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _._AutoID_;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _._AutoID_,
                _._RequestTime_,
                _._AddTime_,
                _._PartDay_,
                _._StatTime_,
                _._IP_,
                _._Language_,
                _._UserAgent_,
                _.AppID,
                _.ServerID,
                _.Type,
                _.AccountID,
                _.UserID,
                _.Number,
                _.ItemType,
                _.Price,
                _.ItemCnt,
                _.MoneyType,
                _.IP,
                _.StatTime,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this.__AutoID_,
                this.__RequestTime_,
                this.__AddTime_,
                this.__PartDay_,
                this.__StatTime_,
                this.__IP_,
                this.__Language_,
                this.__UserAgent_,
                this._AppID,
                this._ServerID,
                this._Type,
                this._AccountID,
                this._UserID,
                this._Number,
                this._ItemType,
                this._Price,
                this._ItemCnt,
                this._MoneyType,
                this._IP,
                this._StatTime,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "H5_Consume_201903");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _AutoID_ = new Field("_AutoID_", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _RequestTime_ = new Field("_RequestTime_", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _AddTime_ = new Field("_AddTime_", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _PartDay_ = new Field("_PartDay_", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _StatTime_ = new Field("_StatTime_", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _IP_ = new Field("_IP_", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _Language_ = new Field("_Language_", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _UserAgent_ = new Field("_UserAgent_", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AppID = new Field("AppID", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ServerID = new Field("ServerID", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AccountID = new Field("AccountID", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserID = new Field("UserID", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Number = new Field("Number", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ItemType = new Field("ItemType", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Price = new Field("Price", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ItemCnt = new Field("ItemCnt", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MoneyType = new Field("MoneyType", "H5_Consume_201903", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IP = new Field("IP", "H5_Consume_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StatTime = new Field("StatTime", "H5_Consume_201903", "");
        }
        #endregion
    }
}