//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Tender.Model
{
    /// <summary>
    /// 实体类H5_Login_201903。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("H5_Login_201903")]
    [Serializable]
    public partial class H5_Login_201903 : Entity
    {
        #region Model
        private long __AutoID_;
        private DateTime __RequestTime_;
        private DateTime __AddTime_;
        private int __PartDay_;
        private DateTime __StatTime_;
        private string __IP_;
        private string __Language_;
        private string __UserAgent_;
        private string _AppID;
        private string _ChannelCode;
        private string _AccountID;
        private string _ServerID;
        private string _UserID;
        private string _DeviceID;
        private string _AppVer;
        private string _DeviceModel;
        private string _ScreenX;
        private string _ScreenY;
        private string _Platform;
        private string _DeviceVer;
        private string _NetMode;
        private string _IP;
        private string _ActType;
        private string _SessionID;
        private int _CreateTime;

        /// <summary>
        /// 
        /// </summary>
        [Field("_AutoID_")]
        public long _AutoID_
        {
            get { return __AutoID_; }
            set
            {
                this.OnPropertyValueChange("_AutoID_");
                this.__AutoID_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_RequestTime_")]
        public DateTime _RequestTime_
        {
            get { return __RequestTime_; }
            set
            {
                this.OnPropertyValueChange("_RequestTime_");
                this.__RequestTime_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_AddTime_")]
        public DateTime _AddTime_
        {
            get { return __AddTime_; }
            set
            {
                this.OnPropertyValueChange("_AddTime_");
                this.__AddTime_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_PartDay_")]
        public int _PartDay_
        {
            get { return __PartDay_; }
            set
            {
                this.OnPropertyValueChange("_PartDay_");
                this.__PartDay_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_StatTime_")]
        public DateTime _StatTime_
        {
            get { return __StatTime_; }
            set
            {
                this.OnPropertyValueChange("_StatTime_");
                this.__StatTime_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_IP_")]
        public string _IP_
        {
            get { return __IP_; }
            set
            {
                this.OnPropertyValueChange("_IP_");
                this.__IP_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_Language_")]
        public string _Language_
        {
            get { return __Language_; }
            set
            {
                this.OnPropertyValueChange("_Language_");
                this.__Language_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_UserAgent_")]
        public string _UserAgent_
        {
            get { return __UserAgent_; }
            set
            {
                this.OnPropertyValueChange("_UserAgent_");
                this.__UserAgent_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AppID")]
        public string AppID
        {
            get { return _AppID; }
            set
            {
                this.OnPropertyValueChange("AppID");
                this._AppID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ChannelCode")]
        public string ChannelCode
        {
            get { return _ChannelCode; }
            set
            {
                this.OnPropertyValueChange("ChannelCode");
                this._ChannelCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AccountID")]
        public string AccountID
        {
            get { return _AccountID; }
            set
            {
                this.OnPropertyValueChange("AccountID");
                this._AccountID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ServerID")]
        public string ServerID
        {
            get { return _ServerID; }
            set
            {
                this.OnPropertyValueChange("ServerID");
                this._ServerID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserID")]
        public string UserID
        {
            get { return _UserID; }
            set
            {
                this.OnPropertyValueChange("UserID");
                this._UserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeviceID")]
        public string DeviceID
        {
            get { return _DeviceID; }
            set
            {
                this.OnPropertyValueChange("DeviceID");
                this._DeviceID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AppVer")]
        public string AppVer
        {
            get { return _AppVer; }
            set
            {
                this.OnPropertyValueChange("AppVer");
                this._AppVer = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeviceModel")]
        public string DeviceModel
        {
            get { return _DeviceModel; }
            set
            {
                this.OnPropertyValueChange("DeviceModel");
                this._DeviceModel = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ScreenX")]
        public string ScreenX
        {
            get { return _ScreenX; }
            set
            {
                this.OnPropertyValueChange("ScreenX");
                this._ScreenX = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ScreenY")]
        public string ScreenY
        {
            get { return _ScreenY; }
            set
            {
                this.OnPropertyValueChange("ScreenY");
                this._ScreenY = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Platform")]
        public string Platform
        {
            get { return _Platform; }
            set
            {
                this.OnPropertyValueChange("Platform");
                this._Platform = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeviceVer")]
        public string DeviceVer
        {
            get { return _DeviceVer; }
            set
            {
                this.OnPropertyValueChange("DeviceVer");
                this._DeviceVer = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("NetMode")]
        public string NetMode
        {
            get { return _NetMode; }
            set
            {
                this.OnPropertyValueChange("NetMode");
                this._NetMode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("IP")]
        public string IP
        {
            get { return _IP; }
            set
            {
                this.OnPropertyValueChange("IP");
                this._IP = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ActType")]
        public string ActType
        {
            get { return _ActType; }
            set
            {
                this.OnPropertyValueChange("ActType");
                this._ActType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SessionID")]
        public string SessionID
        {
            get { return _SessionID; }
            set
            {
                this.OnPropertyValueChange("SessionID");
                this._SessionID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateTime")]
        public int CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange("CreateTime");
                this._CreateTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _._AutoID_,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _._AutoID_;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _._AutoID_,
                _._RequestTime_,
                _._AddTime_,
                _._PartDay_,
                _._StatTime_,
                _._IP_,
                _._Language_,
                _._UserAgent_,
                _.AppID,
                _.ChannelCode,
                _.AccountID,
                _.ServerID,
                _.UserID,
                _.DeviceID,
                _.AppVer,
                _.DeviceModel,
                _.ScreenX,
                _.ScreenY,
                _.Platform,
                _.DeviceVer,
                _.NetMode,
                _.IP,
                _.ActType,
                _.SessionID,
                _.CreateTime,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this.__AutoID_,
                this.__RequestTime_,
                this.__AddTime_,
                this.__PartDay_,
                this.__StatTime_,
                this.__IP_,
                this.__Language_,
                this.__UserAgent_,
                this._AppID,
                this._ChannelCode,
                this._AccountID,
                this._ServerID,
                this._UserID,
                this._DeviceID,
                this._AppVer,
                this._DeviceModel,
                this._ScreenX,
                this._ScreenY,
                this._Platform,
                this._DeviceVer,
                this._NetMode,
                this._IP,
                this._ActType,
                this._SessionID,
                this._CreateTime,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "H5_Login_201903");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _AutoID_ = new Field("_AutoID_", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _RequestTime_ = new Field("_RequestTime_", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _AddTime_ = new Field("_AddTime_", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _PartDay_ = new Field("_PartDay_", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _StatTime_ = new Field("_StatTime_", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _IP_ = new Field("_IP_", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _Language_ = new Field("_Language_", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _UserAgent_ = new Field("_UserAgent_", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AppID = new Field("AppID", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ChannelCode = new Field("ChannelCode", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AccountID = new Field("AccountID", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ServerID = new Field("ServerID", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserID = new Field("UserID", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceID = new Field("DeviceID", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AppVer = new Field("AppVer", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceModel = new Field("DeviceModel", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ScreenX = new Field("ScreenX", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ScreenY = new Field("ScreenY", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Platform = new Field("Platform", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceVer = new Field("DeviceVer", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NetMode = new Field("NetMode", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IP = new Field("IP", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ActType = new Field("ActType", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SessionID = new Field("SessionID", "H5_Login_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "H5_Login_201903", "");
        }
        #endregion
    }
}