//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Tender.Model
{
    /// <summary>
    /// 实体类H5_Online_201903。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("H5_Online_201903")]
    [Serializable]
    public partial class H5_Online_201903 : Entity
    {
        #region Model
        private long __AutoID_;
        private DateTime __RequestTime_;
        private DateTime __AddTime_;
        private int __PartDay_;
        private DateTime __StatTime_;
        private string __IP_;
        private string __Language_;
        private string __UserAgent_;
        private string _AppID;
        private string _ServerName;
        private string _ServerID;
        private string _Platform;
        private string _AccountCnt;
        private int _StatTime;

        /// <summary>
        /// 
        /// </summary>
        [Field("_AutoID_")]
        public long _AutoID_
        {
            get { return __AutoID_; }
            set
            {
                this.OnPropertyValueChange("_AutoID_");
                this.__AutoID_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_RequestTime_")]
        public DateTime _RequestTime_
        {
            get { return __RequestTime_; }
            set
            {
                this.OnPropertyValueChange("_RequestTime_");
                this.__RequestTime_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_AddTime_")]
        public DateTime _AddTime_
        {
            get { return __AddTime_; }
            set
            {
                this.OnPropertyValueChange("_AddTime_");
                this.__AddTime_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_PartDay_")]
        public int _PartDay_
        {
            get { return __PartDay_; }
            set
            {
                this.OnPropertyValueChange("_PartDay_");
                this.__PartDay_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_StatTime_")]
        public DateTime _StatTime_
        {
            get { return __StatTime_; }
            set
            {
                this.OnPropertyValueChange("_StatTime_");
                this.__StatTime_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_IP_")]
        public string _IP_
        {
            get { return __IP_; }
            set
            {
                this.OnPropertyValueChange("_IP_");
                this.__IP_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_Language_")]
        public string _Language_
        {
            get { return __Language_; }
            set
            {
                this.OnPropertyValueChange("_Language_");
                this.__Language_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_UserAgent_")]
        public string _UserAgent_
        {
            get { return __UserAgent_; }
            set
            {
                this.OnPropertyValueChange("_UserAgent_");
                this.__UserAgent_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AppID")]
        public string AppID
        {
            get { return _AppID; }
            set
            {
                this.OnPropertyValueChange("AppID");
                this._AppID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ServerName")]
        public string ServerName
        {
            get { return _ServerName; }
            set
            {
                this.OnPropertyValueChange("ServerName");
                this._ServerName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ServerID")]
        public string ServerID
        {
            get { return _ServerID; }
            set
            {
                this.OnPropertyValueChange("ServerID");
                this._ServerID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Platform")]
        public string Platform
        {
            get { return _Platform; }
            set
            {
                this.OnPropertyValueChange("Platform");
                this._Platform = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AccountCnt")]
        public string AccountCnt
        {
            get { return _AccountCnt; }
            set
            {
                this.OnPropertyValueChange("AccountCnt");
                this._AccountCnt = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("StatTime")]
        public int StatTime
        {
            get { return _StatTime; }
            set
            {
                this.OnPropertyValueChange("StatTime");
                this._StatTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _._AutoID_,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _._AutoID_;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _._AutoID_,
                _._RequestTime_,
                _._AddTime_,
                _._PartDay_,
                _._StatTime_,
                _._IP_,
                _._Language_,
                _._UserAgent_,
                _.AppID,
                _.ServerName,
                _.ServerID,
                _.Platform,
                _.AccountCnt,
                _.StatTime,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this.__AutoID_,
                this.__RequestTime_,
                this.__AddTime_,
                this.__PartDay_,
                this.__StatTime_,
                this.__IP_,
                this.__Language_,
                this.__UserAgent_,
                this._AppID,
                this._ServerName,
                this._ServerID,
                this._Platform,
                this._AccountCnt,
                this._StatTime,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "H5_Online_201903");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _AutoID_ = new Field("_AutoID_", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _RequestTime_ = new Field("_RequestTime_", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _AddTime_ = new Field("_AddTime_", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _PartDay_ = new Field("_PartDay_", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _StatTime_ = new Field("_StatTime_", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _IP_ = new Field("_IP_", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _Language_ = new Field("_Language_", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _UserAgent_ = new Field("_UserAgent_", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AppID = new Field("AppID", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ServerName = new Field("ServerName", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ServerID = new Field("ServerID", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Platform = new Field("Platform", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AccountCnt = new Field("AccountCnt", "H5_Online_201903", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StatTime = new Field("StatTime", "H5_Online_201903", "");
        }
        #endregion
    }
}