//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Tender.Model
{
    /// <summary>
    /// 实体类H5_spend。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("H5_spend")]
    [Serializable]
    public partial class H5_spend : Entity
    {
        #region Model
        private long __AutoID_;
        private DateTime? __LogDate_;
        private long? _CreateTime;
        private int? _ChannelCode;
        private int? _AccountName;
        private int? _ServerID;
        private long? _UserID;
        private int? _VipExp;
        private int? _Fight;
        private int? _Costtype;
        private int? _Subtype;
        private int? _Item_num;
        private int? _MoneyType;
        private int? _MoneyNum;

        /// <summary>
        /// 
        /// </summary>
        [Field("_AutoID_")]
        public long _AutoID_
        {
            get { return __AutoID_; }
            set
            {
                this.OnPropertyValueChange("_AutoID_");
                this.__AutoID_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("_LogDate_")]
        public DateTime? _LogDate_
        {
            get { return __LogDate_; }
            set
            {
                this.OnPropertyValueChange("_LogDate_");
                this.__LogDate_ = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateTime")]
        public long? CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange("CreateTime");
                this._CreateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ChannelCode")]
        public int? ChannelCode
        {
            get { return _ChannelCode; }
            set
            {
                this.OnPropertyValueChange("ChannelCode");
                this._ChannelCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AccountName")]
        public int? AccountName
        {
            get { return _AccountName; }
            set
            {
                this.OnPropertyValueChange("AccountName");
                this._AccountName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ServerID")]
        public int? ServerID
        {
            get { return _ServerID; }
            set
            {
                this.OnPropertyValueChange("ServerID");
                this._ServerID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserID")]
        public long? UserID
        {
            get { return _UserID; }
            set
            {
                this.OnPropertyValueChange("UserID");
                this._UserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("VipExp")]
        public int? VipExp
        {
            get { return _VipExp; }
            set
            {
                this.OnPropertyValueChange("VipExp");
                this._VipExp = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Fight")]
        public int? Fight
        {
            get { return _Fight; }
            set
            {
                this.OnPropertyValueChange("Fight");
                this._Fight = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Field("Costtype")]
        public int? Costtype
        {
            get { return _Costtype; }
            set
            {
                this.OnPropertyValueChange("Costtype");
                this._Costtype = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Subtype")]
        public int? Subtype
        {
            get { return _Subtype; }
            set
            {
                this.OnPropertyValueChange("Subtype");
                this._Subtype = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Item_num")]
        public int? Item_num
        {
            get { return _Item_num; }
            set
            {
                this.OnPropertyValueChange("Item_num");
                this._Item_num = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MoneyType")]
        public int? MoneyType
        {
            get { return _MoneyType; }
            set
            {
                this.OnPropertyValueChange("MoneyType");
                this._MoneyType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MoneyNum")]
        public int? MoneyNum
        {
            get { return _MoneyNum; }
            set
            {
                this.OnPropertyValueChange("MoneyNum");
                this._MoneyNum = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _._AutoID_,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _._AutoID_;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _._AutoID_,
                _._LogDate_,
                _.CreateTime,
                _.ChannelCode,
                _.AccountName,
                _.ServerID,
                _.UserID,
                _.VipExp,
                _.Fight,
                _.Costtype,
                _.Subtype,
                _.Item_num,
                _.MoneyType,
                _.MoneyNum,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this.__AutoID_,
                this.__LogDate_,
                this._CreateTime,
                this._ChannelCode,
                this._AccountName,
                this._ServerID,
                this._UserID,
                this._VipExp,
                this._Fight,
                this._Costtype,
                this._Subtype,
                this._Item_num,
                this._MoneyType,
                this._MoneyNum,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "H5_spend");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _AutoID_ = new Field("_AutoID_", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field _LogDate_ = new Field("_LogDate_", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ChannelCode = new Field("ChannelCode", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AccountName = new Field("AccountName", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ServerID = new Field("ServerID", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserID = new Field("UserID", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VipExp = new Field("VipExp", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Fight = new Field("Fight", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Costtype = new Field("Costtype", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Subtype = new Field("Subtype", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Item_num = new Field("Item_num", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MoneyType = new Field("MoneyType", "H5_spend", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MoneyNum = new Field("MoneyNum", "H5_spend", "");
        }
        #endregion
    }
}