//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Tender
{
    /// <summary>
    /// 实体类tenant_extend_data。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("tenant_extend_data")]
    [Serializable]
    public partial class tenant_extend_data : Entity
    {
        #region Model
        private string _d0;
        private string _id;
        private string _tenant_id;
        private string _create_by;
        private string _create_date;
        private string _update_by;
        private string _update_date;
        private string _b1;
        private string _b2;
        private string _b3;
        private string _b4;
        private string _b5;
        private string _b6;
        private string _b7;
        private string _b8;
        private string _b9;
        private string _b10;
        private string _d1;
        private string _d2;
        private string _d3;
        private string _d4;
        private string _d5;
        private string _dt1;
        private string _dt2;
        private string _dt3;
        private string _dt4;
        private string _dt5;
        private string _n1;
        private string _n2;
        private string _n3;
        private string _n4;
        private string _n5;
        private string _n6;
        private string _n7;
        private string _n8;
        private string _n9;
        private string _n10;
        private string _n11;
        private string _n12;
        private string _n13;
        private string _n14;
        private string _n15;
        private string _n16;
        private string _n17;
        private string _n18;
        private string _n19;
        private string _n20;
        private string _s1;
        private string _s2;
        private string _s3;
        private string _s4;
        private string _s5;
        private string _s6;
        private string _s7;
        private string _s8;
        private string _s9;
        private string _s10;
        private string _s11;
        private string _s12;
        private string _s13;
        private string _s14;
        private string _s15;
        private string _s16;
        private string _s17;
        private string _s18;
        private string _s19;
        private string _s20;
        private string _ms1;
        private string _ms2;
        private string _ms3;
        private string _ms4;
        private string _ms5;
        private string _ms6;
        private string _ms7;
        private string _ms8;
        private string _ms9;
        private string _ms10;
        private string _ms11;
        private string _ms12;
        private string _ms13;
        private string _ms14;
        private string _ms15;
        private string _ms16;
        private string _ms17;
        private string _ms18;
        private string _ms19;
        private string _ms20;
        private string _bs1;
        private string _bs2;
        private string _bs3;
        private string _bs4;
        private string _bs5;
        private string _bs6;
        private string _bs7;
        private string _bs8;
        private string _bs9;
        private string _bs10;
        private string _bs11;
        private string _bs12;
        private string _bs13;
        private string _bs14;
        private string _bs15;
        private string _bs16;
        private string _bs17;
        private string _bs18;
        private string _bs19;
        private string _bs20;
        private string _t1;
        private string _t2;
        private string _t3;
        private string _t4;
        private string _t5;
        private string _t6;
        private string _t7;
        private string _t8;
        private string _t9;
        private string _t10;

        /// <summary>
        /// 
        /// </summary>
        [Field("d0")]
        public string d0
        {
            get { return _d0; }
            set
            {
                this.OnPropertyValueChange("d0");
                this._d0 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("id")]
        public string id
        {
            get { return _id; }
            set
            {
                this.OnPropertyValueChange("id");
                this._id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("tenant_id")]
        public string tenant_id
        {
            get { return _tenant_id; }
            set
            {
                this.OnPropertyValueChange("tenant_id");
                this._tenant_id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("create_by")]
        public string create_by
        {
            get { return _create_by; }
            set
            {
                this.OnPropertyValueChange("create_by");
                this._create_by = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("create_date")]
        public string create_date
        {
            get { return _create_date; }
            set
            {
                this.OnPropertyValueChange("create_date");
                this._create_date = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("update_by")]
        public string update_by
        {
            get { return _update_by; }
            set
            {
                this.OnPropertyValueChange("update_by");
                this._update_by = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("update_date")]
        public string update_date
        {
            get { return _update_date; }
            set
            {
                this.OnPropertyValueChange("update_date");
                this._update_date = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b1")]
        public string b1
        {
            get { return _b1; }
            set
            {
                this.OnPropertyValueChange("b1");
                this._b1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b2")]
        public string b2
        {
            get { return _b2; }
            set
            {
                this.OnPropertyValueChange("b2");
                this._b2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b3")]
        public string b3
        {
            get { return _b3; }
            set
            {
                this.OnPropertyValueChange("b3");
                this._b3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b4")]
        public string b4
        {
            get { return _b4; }
            set
            {
                this.OnPropertyValueChange("b4");
                this._b4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b5")]
        public string b5
        {
            get { return _b5; }
            set
            {
                this.OnPropertyValueChange("b5");
                this._b5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b6")]
        public string b6
        {
            get { return _b6; }
            set
            {
                this.OnPropertyValueChange("b6");
                this._b6 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b7")]
        public string b7
        {
            get { return _b7; }
            set
            {
                this.OnPropertyValueChange("b7");
                this._b7 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b8")]
        public string b8
        {
            get { return _b8; }
            set
            {
                this.OnPropertyValueChange("b8");
                this._b8 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b9")]
        public string b9
        {
            get { return _b9; }
            set
            {
                this.OnPropertyValueChange("b9");
                this._b9 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("b10")]
        public string b10
        {
            get { return _b10; }
            set
            {
                this.OnPropertyValueChange("b10");
                this._b10 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("d1")]
        public string d1
        {
            get { return _d1; }
            set
            {
                this.OnPropertyValueChange("d1");
                this._d1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("d2")]
        public string d2
        {
            get { return _d2; }
            set
            {
                this.OnPropertyValueChange("d2");
                this._d2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("d3")]
        public string d3
        {
            get { return _d3; }
            set
            {
                this.OnPropertyValueChange("d3");
                this._d3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("d4")]
        public string d4
        {
            get { return _d4; }
            set
            {
                this.OnPropertyValueChange("d4");
                this._d4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("d5")]
        public string d5
        {
            get { return _d5; }
            set
            {
                this.OnPropertyValueChange("d5");
                this._d5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("dt1")]
        public string dt1
        {
            get { return _dt1; }
            set
            {
                this.OnPropertyValueChange("dt1");
                this._dt1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("dt2")]
        public string dt2
        {
            get { return _dt2; }
            set
            {
                this.OnPropertyValueChange("dt2");
                this._dt2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("dt3")]
        public string dt3
        {
            get { return _dt3; }
            set
            {
                this.OnPropertyValueChange("dt3");
                this._dt3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("dt4")]
        public string dt4
        {
            get { return _dt4; }
            set
            {
                this.OnPropertyValueChange("dt4");
                this._dt4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("dt5")]
        public string dt5
        {
            get { return _dt5; }
            set
            {
                this.OnPropertyValueChange("dt5");
                this._dt5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n1")]
        public string n1
        {
            get { return _n1; }
            set
            {
                this.OnPropertyValueChange("n1");
                this._n1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n2")]
        public string n2
        {
            get { return _n2; }
            set
            {
                this.OnPropertyValueChange("n2");
                this._n2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n3")]
        public string n3
        {
            get { return _n3; }
            set
            {
                this.OnPropertyValueChange("n3");
                this._n3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n4")]
        public string n4
        {
            get { return _n4; }
            set
            {
                this.OnPropertyValueChange("n4");
                this._n4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n5")]
        public string n5
        {
            get { return _n5; }
            set
            {
                this.OnPropertyValueChange("n5");
                this._n5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n6")]
        public string n6
        {
            get { return _n6; }
            set
            {
                this.OnPropertyValueChange("n6");
                this._n6 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n7")]
        public string n7
        {
            get { return _n7; }
            set
            {
                this.OnPropertyValueChange("n7");
                this._n7 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n8")]
        public string n8
        {
            get { return _n8; }
            set
            {
                this.OnPropertyValueChange("n8");
                this._n8 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n9")]
        public string n9
        {
            get { return _n9; }
            set
            {
                this.OnPropertyValueChange("n9");
                this._n9 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n10")]
        public string n10
        {
            get { return _n10; }
            set
            {
                this.OnPropertyValueChange("n10");
                this._n10 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n11")]
        public string n11
        {
            get { return _n11; }
            set
            {
                this.OnPropertyValueChange("n11");
                this._n11 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n12")]
        public string n12
        {
            get { return _n12; }
            set
            {
                this.OnPropertyValueChange("n12");
                this._n12 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n13")]
        public string n13
        {
            get { return _n13; }
            set
            {
                this.OnPropertyValueChange("n13");
                this._n13 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n14")]
        public string n14
        {
            get { return _n14; }
            set
            {
                this.OnPropertyValueChange("n14");
                this._n14 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n15")]
        public string n15
        {
            get { return _n15; }
            set
            {
                this.OnPropertyValueChange("n15");
                this._n15 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n16")]
        public string n16
        {
            get { return _n16; }
            set
            {
                this.OnPropertyValueChange("n16");
                this._n16 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n17")]
        public string n17
        {
            get { return _n17; }
            set
            {
                this.OnPropertyValueChange("n17");
                this._n17 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n18")]
        public string n18
        {
            get { return _n18; }
            set
            {
                this.OnPropertyValueChange("n18");
                this._n18 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n19")]
        public string n19
        {
            get { return _n19; }
            set
            {
                this.OnPropertyValueChange("n19");
                this._n19 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("n20")]
        public string n20
        {
            get { return _n20; }
            set
            {
                this.OnPropertyValueChange("n20");
                this._n20 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s1")]
        public string s1
        {
            get { return _s1; }
            set
            {
                this.OnPropertyValueChange("s1");
                this._s1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s2")]
        public string s2
        {
            get { return _s2; }
            set
            {
                this.OnPropertyValueChange("s2");
                this._s2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s3")]
        public string s3
        {
            get { return _s3; }
            set
            {
                this.OnPropertyValueChange("s3");
                this._s3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s4")]
        public string s4
        {
            get { return _s4; }
            set
            {
                this.OnPropertyValueChange("s4");
                this._s4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s5")]
        public string s5
        {
            get { return _s5; }
            set
            {
                this.OnPropertyValueChange("s5");
                this._s5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s6")]
        public string s6
        {
            get { return _s6; }
            set
            {
                this.OnPropertyValueChange("s6");
                this._s6 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s7")]
        public string s7
        {
            get { return _s7; }
            set
            {
                this.OnPropertyValueChange("s7");
                this._s7 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s8")]
        public string s8
        {
            get { return _s8; }
            set
            {
                this.OnPropertyValueChange("s8");
                this._s8 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s9")]
        public string s9
        {
            get { return _s9; }
            set
            {
                this.OnPropertyValueChange("s9");
                this._s9 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s10")]
        public string s10
        {
            get { return _s10; }
            set
            {
                this.OnPropertyValueChange("s10");
                this._s10 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s11")]
        public string s11
        {
            get { return _s11; }
            set
            {
                this.OnPropertyValueChange("s11");
                this._s11 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s12")]
        public string s12
        {
            get { return _s12; }
            set
            {
                this.OnPropertyValueChange("s12");
                this._s12 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s13")]
        public string s13
        {
            get { return _s13; }
            set
            {
                this.OnPropertyValueChange("s13");
                this._s13 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s14")]
        public string s14
        {
            get { return _s14; }
            set
            {
                this.OnPropertyValueChange("s14");
                this._s14 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s15")]
        public string s15
        {
            get { return _s15; }
            set
            {
                this.OnPropertyValueChange("s15");
                this._s15 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s16")]
        public string s16
        {
            get { return _s16; }
            set
            {
                this.OnPropertyValueChange("s16");
                this._s16 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s17")]
        public string s17
        {
            get { return _s17; }
            set
            {
                this.OnPropertyValueChange("s17");
                this._s17 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s18")]
        public string s18
        {
            get { return _s18; }
            set
            {
                this.OnPropertyValueChange("s18");
                this._s18 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s19")]
        public string s19
        {
            get { return _s19; }
            set
            {
                this.OnPropertyValueChange("s19");
                this._s19 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("s20")]
        public string s20
        {
            get { return _s20; }
            set
            {
                this.OnPropertyValueChange("s20");
                this._s20 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms1")]
        public string ms1
        {
            get { return _ms1; }
            set
            {
                this.OnPropertyValueChange("ms1");
                this._ms1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms2")]
        public string ms2
        {
            get { return _ms2; }
            set
            {
                this.OnPropertyValueChange("ms2");
                this._ms2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms3")]
        public string ms3
        {
            get { return _ms3; }
            set
            {
                this.OnPropertyValueChange("ms3");
                this._ms3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms4")]
        public string ms4
        {
            get { return _ms4; }
            set
            {
                this.OnPropertyValueChange("ms4");
                this._ms4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms5")]
        public string ms5
        {
            get { return _ms5; }
            set
            {
                this.OnPropertyValueChange("ms5");
                this._ms5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms6")]
        public string ms6
        {
            get { return _ms6; }
            set
            {
                this.OnPropertyValueChange("ms6");
                this._ms6 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms7")]
        public string ms7
        {
            get { return _ms7; }
            set
            {
                this.OnPropertyValueChange("ms7");
                this._ms7 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms8")]
        public string ms8
        {
            get { return _ms8; }
            set
            {
                this.OnPropertyValueChange("ms8");
                this._ms8 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms9")]
        public string ms9
        {
            get { return _ms9; }
            set
            {
                this.OnPropertyValueChange("ms9");
                this._ms9 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms10")]
        public string ms10
        {
            get { return _ms10; }
            set
            {
                this.OnPropertyValueChange("ms10");
                this._ms10 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms11")]
        public string ms11
        {
            get { return _ms11; }
            set
            {
                this.OnPropertyValueChange("ms11");
                this._ms11 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms12")]
        public string ms12
        {
            get { return _ms12; }
            set
            {
                this.OnPropertyValueChange("ms12");
                this._ms12 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms13")]
        public string ms13
        {
            get { return _ms13; }
            set
            {
                this.OnPropertyValueChange("ms13");
                this._ms13 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms14")]
        public string ms14
        {
            get { return _ms14; }
            set
            {
                this.OnPropertyValueChange("ms14");
                this._ms14 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms15")]
        public string ms15
        {
            get { return _ms15; }
            set
            {
                this.OnPropertyValueChange("ms15");
                this._ms15 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms16")]
        public string ms16
        {
            get { return _ms16; }
            set
            {
                this.OnPropertyValueChange("ms16");
                this._ms16 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms17")]
        public string ms17
        {
            get { return _ms17; }
            set
            {
                this.OnPropertyValueChange("ms17");
                this._ms17 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms18")]
        public string ms18
        {
            get { return _ms18; }
            set
            {
                this.OnPropertyValueChange("ms18");
                this._ms18 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms19")]
        public string ms19
        {
            get { return _ms19; }
            set
            {
                this.OnPropertyValueChange("ms19");
                this._ms19 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ms20")]
        public string ms20
        {
            get { return _ms20; }
            set
            {
                this.OnPropertyValueChange("ms20");
                this._ms20 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs1")]
        public string bs1
        {
            get { return _bs1; }
            set
            {
                this.OnPropertyValueChange("bs1");
                this._bs1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs2")]
        public string bs2
        {
            get { return _bs2; }
            set
            {
                this.OnPropertyValueChange("bs2");
                this._bs2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs3")]
        public string bs3
        {
            get { return _bs3; }
            set
            {
                this.OnPropertyValueChange("bs3");
                this._bs3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs4")]
        public string bs4
        {
            get { return _bs4; }
            set
            {
                this.OnPropertyValueChange("bs4");
                this._bs4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs5")]
        public string bs5
        {
            get { return _bs5; }
            set
            {
                this.OnPropertyValueChange("bs5");
                this._bs5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs6")]
        public string bs6
        {
            get { return _bs6; }
            set
            {
                this.OnPropertyValueChange("bs6");
                this._bs6 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs7")]
        public string bs7
        {
            get { return _bs7; }
            set
            {
                this.OnPropertyValueChange("bs7");
                this._bs7 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs8")]
        public string bs8
        {
            get { return _bs8; }
            set
            {
                this.OnPropertyValueChange("bs8");
                this._bs8 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs9")]
        public string bs9
        {
            get { return _bs9; }
            set
            {
                this.OnPropertyValueChange("bs9");
                this._bs9 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs10")]
        public string bs10
        {
            get { return _bs10; }
            set
            {
                this.OnPropertyValueChange("bs10");
                this._bs10 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs11")]
        public string bs11
        {
            get { return _bs11; }
            set
            {
                this.OnPropertyValueChange("bs11");
                this._bs11 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs12")]
        public string bs12
        {
            get { return _bs12; }
            set
            {
                this.OnPropertyValueChange("bs12");
                this._bs12 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs13")]
        public string bs13
        {
            get { return _bs13; }
            set
            {
                this.OnPropertyValueChange("bs13");
                this._bs13 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs14")]
        public string bs14
        {
            get { return _bs14; }
            set
            {
                this.OnPropertyValueChange("bs14");
                this._bs14 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs15")]
        public string bs15
        {
            get { return _bs15; }
            set
            {
                this.OnPropertyValueChange("bs15");
                this._bs15 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs16")]
        public string bs16
        {
            get { return _bs16; }
            set
            {
                this.OnPropertyValueChange("bs16");
                this._bs16 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs17")]
        public string bs17
        {
            get { return _bs17; }
            set
            {
                this.OnPropertyValueChange("bs17");
                this._bs17 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs18")]
        public string bs18
        {
            get { return _bs18; }
            set
            {
                this.OnPropertyValueChange("bs18");
                this._bs18 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs19")]
        public string bs19
        {
            get { return _bs19; }
            set
            {
                this.OnPropertyValueChange("bs19");
                this._bs19 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("bs20")]
        public string bs20
        {
            get { return _bs20; }
            set
            {
                this.OnPropertyValueChange("bs20");
                this._bs20 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t1")]
        public string t1
        {
            get { return _t1; }
            set
            {
                this.OnPropertyValueChange("t1");
                this._t1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t2")]
        public string t2
        {
            get { return _t2; }
            set
            {
                this.OnPropertyValueChange("t2");
                this._t2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t3")]
        public string t3
        {
            get { return _t3; }
            set
            {
                this.OnPropertyValueChange("t3");
                this._t3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t4")]
        public string t4
        {
            get { return _t4; }
            set
            {
                this.OnPropertyValueChange("t4");
                this._t4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t5")]
        public string t5
        {
            get { return _t5; }
            set
            {
                this.OnPropertyValueChange("t5");
                this._t5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t6")]
        public string t6
        {
            get { return _t6; }
            set
            {
                this.OnPropertyValueChange("t6");
                this._t6 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t7")]
        public string t7
        {
            get { return _t7; }
            set
            {
                this.OnPropertyValueChange("t7");
                this._t7 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t8")]
        public string t8
        {
            get { return _t8; }
            set
            {
                this.OnPropertyValueChange("t8");
                this._t8 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t9")]
        public string t9
        {
            get { return _t9; }
            set
            {
                this.OnPropertyValueChange("t9");
                this._t9 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("t10")]
        public string t10
        {
            get { return _t10; }
            set
            {
                this.OnPropertyValueChange("t10");
                this._t10 = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.d0,
                _.id,
                _.tenant_id,
                _.create_by,
                _.create_date,
                _.update_by,
                _.update_date,
                _.b1,
                _.b2,
                _.b3,
                _.b4,
                _.b5,
                _.b6,
                _.b7,
                _.b8,
                _.b9,
                _.b10,
                _.d1,
                _.d2,
                _.d3,
                _.d4,
                _.d5,
                _.dt1,
                _.dt2,
                _.dt3,
                _.dt4,
                _.dt5,
                _.n1,
                _.n2,
                _.n3,
                _.n4,
                _.n5,
                _.n6,
                _.n7,
                _.n8,
                _.n9,
                _.n10,
                _.n11,
                _.n12,
                _.n13,
                _.n14,
                _.n15,
                _.n16,
                _.n17,
                _.n18,
                _.n19,
                _.n20,
                _.s1,
                _.s2,
                _.s3,
                _.s4,
                _.s5,
                _.s6,
                _.s7,
                _.s8,
                _.s9,
                _.s10,
                _.s11,
                _.s12,
                _.s13,
                _.s14,
                _.s15,
                _.s16,
                _.s17,
                _.s18,
                _.s19,
                _.s20,
                _.ms1,
                _.ms2,
                _.ms3,
                _.ms4,
                _.ms5,
                _.ms6,
                _.ms7,
                _.ms8,
                _.ms9,
                _.ms10,
                _.ms11,
                _.ms12,
                _.ms13,
                _.ms14,
                _.ms15,
                _.ms16,
                _.ms17,
                _.ms18,
                _.ms19,
                _.ms20,
                _.bs1,
                _.bs2,
                _.bs3,
                _.bs4,
                _.bs5,
                _.bs6,
                _.bs7,
                _.bs8,
                _.bs9,
                _.bs10,
                _.bs11,
                _.bs12,
                _.bs13,
                _.bs14,
                _.bs15,
                _.bs16,
                _.bs17,
                _.bs18,
                _.bs19,
                _.bs20,
                _.t1,
                _.t2,
                _.t3,
                _.t4,
                _.t5,
                _.t6,
                _.t7,
                _.t8,
                _.t9,
                _.t10,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._d0,
                this._id,
                this._tenant_id,
                this._create_by,
                this._create_date,
                this._update_by,
                this._update_date,
                this._b1,
                this._b2,
                this._b3,
                this._b4,
                this._b5,
                this._b6,
                this._b7,
                this._b8,
                this._b9,
                this._b10,
                this._d1,
                this._d2,
                this._d3,
                this._d4,
                this._d5,
                this._dt1,
                this._dt2,
                this._dt3,
                this._dt4,
                this._dt5,
                this._n1,
                this._n2,
                this._n3,
                this._n4,
                this._n5,
                this._n6,
                this._n7,
                this._n8,
                this._n9,
                this._n10,
                this._n11,
                this._n12,
                this._n13,
                this._n14,
                this._n15,
                this._n16,
                this._n17,
                this._n18,
                this._n19,
                this._n20,
                this._s1,
                this._s2,
                this._s3,
                this._s4,
                this._s5,
                this._s6,
                this._s7,
                this._s8,
                this._s9,
                this._s10,
                this._s11,
                this._s12,
                this._s13,
                this._s14,
                this._s15,
                this._s16,
                this._s17,
                this._s18,
                this._s19,
                this._s20,
                this._ms1,
                this._ms2,
                this._ms3,
                this._ms4,
                this._ms5,
                this._ms6,
                this._ms7,
                this._ms8,
                this._ms9,
                this._ms10,
                this._ms11,
                this._ms12,
                this._ms13,
                this._ms14,
                this._ms15,
                this._ms16,
                this._ms17,
                this._ms18,
                this._ms19,
                this._ms20,
                this._bs1,
                this._bs2,
                this._bs3,
                this._bs4,
                this._bs5,
                this._bs6,
                this._bs7,
                this._bs8,
                this._bs9,
                this._bs10,
                this._bs11,
                this._bs12,
                this._bs13,
                this._bs14,
                this._bs15,
                this._bs16,
                this._bs17,
                this._bs18,
                this._bs19,
                this._bs20,
                this._t1,
                this._t2,
                this._t3,
                this._t4,
                this._t5,
                this._t6,
                this._t7,
                this._t8,
                this._t9,
                this._t10,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "tenant_extend_data");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field d0 = new Field("d0", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field tenant_id = new Field("tenant_id", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field create_by = new Field("create_by", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field create_date = new Field("create_date", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field update_by = new Field("update_by", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field update_date = new Field("update_date", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b1 = new Field("b1", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b2 = new Field("b2", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b3 = new Field("b3", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b4 = new Field("b4", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b5 = new Field("b5", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b6 = new Field("b6", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b7 = new Field("b7", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b8 = new Field("b8", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b9 = new Field("b9", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field b10 = new Field("b10", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field d1 = new Field("d1", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field d2 = new Field("d2", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field d3 = new Field("d3", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field d4 = new Field("d4", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field d5 = new Field("d5", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field dt1 = new Field("dt1", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field dt2 = new Field("dt2", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field dt3 = new Field("dt3", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field dt4 = new Field("dt4", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field dt5 = new Field("dt5", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n1 = new Field("n1", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n2 = new Field("n2", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n3 = new Field("n3", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n4 = new Field("n4", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n5 = new Field("n5", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n6 = new Field("n6", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n7 = new Field("n7", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n8 = new Field("n8", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n9 = new Field("n9", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n10 = new Field("n10", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n11 = new Field("n11", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n12 = new Field("n12", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n13 = new Field("n13", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n14 = new Field("n14", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n15 = new Field("n15", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n16 = new Field("n16", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n17 = new Field("n17", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n18 = new Field("n18", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n19 = new Field("n19", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field n20 = new Field("n20", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s1 = new Field("s1", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s2 = new Field("s2", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s3 = new Field("s3", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s4 = new Field("s4", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s5 = new Field("s5", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s6 = new Field("s6", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s7 = new Field("s7", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s8 = new Field("s8", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s9 = new Field("s9", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s10 = new Field("s10", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s11 = new Field("s11", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s12 = new Field("s12", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s13 = new Field("s13", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s14 = new Field("s14", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s15 = new Field("s15", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s16 = new Field("s16", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s17 = new Field("s17", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s18 = new Field("s18", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s19 = new Field("s19", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field s20 = new Field("s20", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms1 = new Field("ms1", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms2 = new Field("ms2", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms3 = new Field("ms3", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms4 = new Field("ms4", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms5 = new Field("ms5", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms6 = new Field("ms6", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms7 = new Field("ms7", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms8 = new Field("ms8", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms9 = new Field("ms9", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms10 = new Field("ms10", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms11 = new Field("ms11", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms12 = new Field("ms12", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms13 = new Field("ms13", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms14 = new Field("ms14", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms15 = new Field("ms15", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms16 = new Field("ms16", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms17 = new Field("ms17", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms18 = new Field("ms18", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms19 = new Field("ms19", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ms20 = new Field("ms20", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs1 = new Field("bs1", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs2 = new Field("bs2", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs3 = new Field("bs3", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs4 = new Field("bs4", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs5 = new Field("bs5", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs6 = new Field("bs6", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs7 = new Field("bs7", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs8 = new Field("bs8", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs9 = new Field("bs9", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs10 = new Field("bs10", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs11 = new Field("bs11", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs12 = new Field("bs12", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs13 = new Field("bs13", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs14 = new Field("bs14", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs15 = new Field("bs15", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs16 = new Field("bs16", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs17 = new Field("bs17", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs18 = new Field("bs18", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs19 = new Field("bs19", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field bs20 = new Field("bs20", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t1 = new Field("t1", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t2 = new Field("t2", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t3 = new Field("t3", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t4 = new Field("t4", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t5 = new Field("t5", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t6 = new Field("t6", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t7 = new Field("t7", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t8 = new Field("t8", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t9 = new Field("t9", "tenant_extend_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field t10 = new Field("t10", "tenant_extend_data", "");
        }
        #endregion
    }
}