//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Tender
{
    /// <summary>
    /// 实体类Tender。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Tender")]
    [Serializable]
    public partial class Tender : Entity
    {
        #region Model
        private long _AutoID;
        private DateTime? _StatDate;
        private string _BusinessName;
        private string _KeyWord;
        private string _Area;
        private string _BulletinTime;
        private string _Name;
        private string _Catalogue;
        private string _Budget;
        private string _BidTime;
        private string _BidAddress;
        private string _FileAddress;
        private string _FileTime;
        private string _PurchaseUnit;
        private string _ContactPeople;
        private string _ContactPhone;
        private string _AgentName;
        private string _AgentContact;

        /// <summary>
        /// 
        /// </summary>
        [Field("AutoID")]
        public long AutoID
        {
            get { return _AutoID; }
            set
            {
                this.OnPropertyValueChange("AutoID");
                this._AutoID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("StatDate")]
        public DateTime? StatDate
        {
            get { return _StatDate; }
            set
            {
                this.OnPropertyValueChange("StatDate");
                this._StatDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("BusinessName")]
        public string BusinessName
        {
            get { return _BusinessName; }
            set
            {
                this.OnPropertyValueChange("BusinessName");
                this._BusinessName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("KeyWord")]
        public string KeyWord
        {
            get { return _KeyWord; }
            set
            {
                this.OnPropertyValueChange("KeyWord");
                this._KeyWord = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Area")]
        public string Area
        {
            get { return _Area; }
            set
            {
                this.OnPropertyValueChange("Area");
                this._Area = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("BulletinTime")]
        public string BulletinTime
        {
            get { return _BulletinTime; }
            set
            {
                this.OnPropertyValueChange("BulletinTime");
                this._BulletinTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Name")]
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange("Name");
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Catalogue")]
        public string Catalogue
        {
            get { return _Catalogue; }
            set
            {
                this.OnPropertyValueChange("Catalogue");
                this._Catalogue = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Budget")]
        public string Budget
        {
            get { return _Budget; }
            set
            {
                this.OnPropertyValueChange("Budget");
                this._Budget = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("BidTime")]
        public string BidTime
        {
            get { return _BidTime; }
            set
            {
                this.OnPropertyValueChange("BidTime");
                this._BidTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("BidAddress")]
        public string BidAddress
        {
            get { return _BidAddress; }
            set
            {
                this.OnPropertyValueChange("BidAddress");
                this._BidAddress = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("FileAddress")]
        public string FileAddress
        {
            get { return _FileAddress; }
            set
            {
                this.OnPropertyValueChange("FileAddress");
                this._FileAddress = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("FileTime")]
        public string FileTime
        {
            get { return _FileTime; }
            set
            {
                this.OnPropertyValueChange("FileTime");
                this._FileTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PurchaseUnit")]
        public string PurchaseUnit
        {
            get { return _PurchaseUnit; }
            set
            {
                this.OnPropertyValueChange("PurchaseUnit");
                this._PurchaseUnit = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ContactPeople")]
        public string ContactPeople
        {
            get { return _ContactPeople; }
            set
            {
                this.OnPropertyValueChange("ContactPeople");
                this._ContactPeople = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ContactPhone")]
        public string ContactPhone
        {
            get { return _ContactPhone; }
            set
            {
                this.OnPropertyValueChange("ContactPhone");
                this._ContactPhone = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AgentName")]
        public string AgentName
        {
            get { return _AgentName; }
            set
            {
                this.OnPropertyValueChange("AgentName");
                this._AgentName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AgentContact")]
        public string AgentContact
        {
            get { return _AgentContact; }
            set
            {
                this.OnPropertyValueChange("AgentContact");
                this._AgentContact = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.AutoID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.AutoID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.AutoID,
                _.StatDate,
                _.BusinessName,
                _.KeyWord,
                _.Area,
                _.BulletinTime,
                _.Name,
                _.Catalogue,
                _.Budget,
                _.BidTime,
                _.BidAddress,
                _.FileAddress,
                _.FileTime,
                _.PurchaseUnit,
                _.ContactPeople,
                _.ContactPhone,
                _.AgentName,
                _.AgentContact,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._AutoID,
                this._StatDate,
                this._BusinessName,
                this._KeyWord,
                this._Area,
                this._BulletinTime,
                this._Name,
                this._Catalogue,
                this._Budget,
                this._BidTime,
                this._BidAddress,
                this._FileAddress,
                this._FileTime,
                this._PurchaseUnit,
                this._ContactPeople,
                this._ContactPhone,
                this._AgentName,
                this._AgentContact,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Tender");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AutoID = new Field("AutoID", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StatDate = new Field("StatDate", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BusinessName = new Field("BusinessName", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field KeyWord = new Field("KeyWord", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Area = new Field("Area", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BulletinTime = new Field("BulletinTime", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Catalogue = new Field("Catalogue", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Budget = new Field("Budget", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BidTime = new Field("BidTime", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BidAddress = new Field("BidAddress", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FileAddress = new Field("FileAddress", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FileTime = new Field("FileTime", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PurchaseUnit = new Field("PurchaseUnit", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ContactPeople = new Field("ContactPeople", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ContactPhone = new Field("ContactPhone", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AgentName = new Field("AgentName", "Tender", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AgentContact = new Field("AgentContact", "Tender", "");
        }
        #endregion
    }
}