//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Tender
{
    /// <summary>
    /// 实体类Tender_Setting。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Tender_Setting")]
    [Serializable]
    public partial class Tender_Setting : Entity
    {
        #region Model
        private long _AutoID;
        private string _Name;
        private string _KeyWord;

        /// <summary>
        /// 
        /// </summary>
        [Field("AutoID")]
        public long AutoID
        {
            get { return _AutoID; }
            set
            {
                this.OnPropertyValueChange("AutoID");
                this._AutoID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Name")]
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange("Name");
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("KeyWord")]
        public string KeyWord
        {
            get { return _KeyWord; }
            set
            {
                this.OnPropertyValueChange("KeyWord");
                this._KeyWord = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.AutoID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.AutoID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.AutoID,
                _.Name,
                _.KeyWord,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._AutoID,
                this._Name,
                this._KeyWord,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Tender_Setting");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AutoID = new Field("AutoID", "Tender_Setting", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "Tender_Setting", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field KeyWord = new Field("KeyWord", "Tender_Setting", "");
        }
        #endregion
    }
}